site_name: DisGo Wiki
site_description: DisGo Wiki
site_author: TopiSenpai
copyright: Copyright 2022 TopiSenpai, Skye-31

watch:
  - templates

extra_javascript:
  - path: 'assets/scripts/extra_script.js'

extra_css:
  - 'assets/stylesheets/colors.css'
  - 'assets/stylesheets/style.css'

nav:
  - DisGo:
    - Features: disgo/features.md
    - Getting Started: disgo/index.md
    - Examples: disgo/examples.md
    - disgo Package: disgo/packages/disgo.md
    - discord: disgo/packages/discord.md
    - bot: disgo/packages/bot.md
    - gateway: disgo/packages/gateway.md
    - sharding: disgo/packages/sharding.md
    - cache: disgo/packages/cache.md
    - httpserver: disgo/packages/httpserver.md
    - events: disgo/packages/events.md
    - rest: disgo/packages/rest.md
    - webhook: disgo/packages/webhook.md
    - oauth2: disgo/packages/oauth2.md
    - voice: disgo/packages/voice.md
  - DisGoLink:
    - Getting Started: disgolink/index.md
    - Examples: disgolink/examples.md
    - Events: disgolink/events.md
    - Plugins: disgolink/plugins.md

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - open-in-new-tab

markdown_extensions:
  - admonition
  - meta
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - footnotes
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

theme:
  custom_dir: templates
  favicon: assets/images/logo.png
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - content.code.annotate
  name: material
  logo: assets/images/logo.png
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: #5865F2
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: #5865F2
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

repo_name: disgo
repo_url: https://github.com/disgoorg/disgo
edit_uri: ../disgo-wiki/edit/master/docs/
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/disgoorg
    - icon: fontawesome/brands/discord
      link: https://discord.gg/9tKpqXjYVC