# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: DisGo Wiki
site_description: DisGo Wiki
site_author: topi314
copyright: Copyright 2025 topi314, Skye-31

watch:
  - overrides

extra_css:
  - 'assets/stylesheets/colors.css'
  - 'assets/stylesheets/style.css'

use_directory_urls: true
nav:
  - Home: index.md
  - DisGo:
    - disgo/index.md
    - Getting Started: disgo/getting-started.md
  - DisGoLink:
    - disgolink/index.md
    - Getting Started: disgolink/getting-started.md

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions:
  - admonition
  - meta
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - footnotes
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

theme:
  custom_dir: overrides
  favicon: assets/images/logo.png
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - navigation.indexes
    - toc.integrate
    - content.code.annotate
    - announce.dismiss
  name: material
  logo: assets/images/logo.png
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: #5865F2
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: #5865F2
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

repo_name: disgo
repo_url: https://github.com/disgoorg/disgo
edit_uri: ../disgo-wiki/edit/master/docs/
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/disgoorg
    - icon: fontawesome/brands/discord
      link: https://discord.gg/9tKpqXjYVC
